# Crash Information
AppName: Victoria 3 
AppVersion: 1.13.11 
SCMBranch: release/1.13.11 
SCMCommit: 15aa89ae429b6bcff8d195f2a650f98ba95cd64c 
SCMTimeStamp: "2026-08-18 13:14:44 +0000" 
DateTime: "0126-08-08 03:34:00 +0900" 
BuildType: ReleaseLto 
Platform: Windows 
Store: steam 
Architecture: 64-bit 
OperatingSystem: Windows 11 (Build 26200) 
SystemLanguage: ja 
CPUModel: 12th Gen Intel(R) Core(TM) i9-12900K 
CPUSpeed: 3187 
CPUPhysicalCores: 16 
CPULogicalCores: 24 
SystemMemoryAvailable: 11329 
SystemMemory: 32541 
SwapSizeAvailable: 13462 
SwapSize: 58141 
GPUName: AMD Radeon RX 9070 XT 
GPUVendor: AMD 
GPUId: 30032 
GPUDedicatedMemory: 16188 
LaunchArguments: --debugmode --gdprcompliant --paradoxaccountuserid="" --pdxlaunchersessiontoken="" 
DLC_1: Voice of the People Preorder 
DLC_2: Pivot of Empire 
DLC_3: Victoria 2 Remastered Soundtrack 
DLC_4: National Awakening 
DLC_5: The Great Wave 
DLC_6: Songs of the Homeland 
DLC_7: Region Pack 1 
DLC_8: Free Trains Pack 
DLC_9: Sphere of Influence 
DLC_10: Dawn of Wonder 
DLC_11: Warships Bonus Pack 
DLC_12: Trade Ships Bonus Pack 
DLC_13: Charters of Commerce 
DLC_14: Voice of the People 
DLC_15: American Buildings Pack 
DLC_16: Melodies for the Masses 
DLC_17: Iberian Twilight 
Mod_1: Twilight of Empires 
