l_english:
#Anbennar - replaced all instances of Diesel with Heavy Oil
pm_diesel_engines:0 "Heavy Oil Engines"
pm_photographic_art:0 "Viewcatcher Art" 
pm_diesel_pump_building_coal_mine:0 "Heavy Oil Pump" 
pm_diesel_pump_building_iron_mine:0 "Heavy Oil Pump" 
pm_diesel_pump_building_lead_mine:0 "Heavy Oil Pump" 
pm_diesel_pump_building_sulfur_mine:0 "Heavy Oil Pump" 
pm_diesel_pump_building_gold_mine:0 "Heavy Oil Pump"